### PR TITLE
Create aboutlibraries_strings.xml

### PR DESCRIPTION
**Pull request by kashban**
Please add this file to your distribution. It allows to simply display the licence in any app using it by including https://github.com/mikepenz/AboutLibraries.

### CODE REVIEW

**Comment by piruin** [comment]
Interesting!! 
 but I try to build AboutLibraries's string file with [AboutLibrary definition-file builder](http://def-builder.mikepenz.com/), It have little different from your `aboutlibraries_string.xml`

Are both correct?

here what it got
```xml
<?xml version="1.0" encoding="utf-8"?>

<resources>
	<string name="define_quickaction"></string>
	<!-- Author section -->
	<string name="library_quickaction_author">Blast Piruin Panichphol</string>
	<string name="library_quickaction_authorWebsite">piruin.me</string>
	<!-- Library section -->
	<string name="library_quickaction_libraryName">QuickAction</string>
	<string name="library_quickaction_libraryDescription">QuickAction is a small android library for easy create Tooltips with some action or just as decoration. Original by http://www.londatiga.net/</string>
	<string name="library_quickaction_libraryWebsite">http://piruin.me/quickaction/</string>
	<string name="library_quickaction_libraryVersion">2</string>
	<!-- OpenSource section -->
	<string name="library_quickaction_isOpenSource">true</string>
	<string name="library_quickaction_repositoryLink">https://github.com/piruin/quickaction</string>
	<!-- ClassPath for autoDetect section -->
	<string name="library_quickaction_classPath">me.piruin.quickaction</string>
	<!-- License section -->
	<string name="library_quickaction_licenseId">apache_2_0</string>
	<!-- Custom variables section -->
</resources>
```

**Comment by kashban** [comment]
I took my sample from here: https://github.com/mikepenz/AboutLibraries/wiki/HOWTODEV:-Include-in-your-library. Obviously I made a copy / paste mistake with "define_QuickAction" instead of Quickaction". I will correct the PR.

**Comment by kashban** [comment]
I am sorry, something went wrong with this PR. The file should be in quickaction/quickaction/src/main/res/values/, not quickaction/res/values/. I will try to create a new one with the correct destination directory later.

**Comment by kashban** [comment]
Ok, the problem is that the directory structure of your project and the original you forked from are different. I cannot create PRs directly for your project, only for the original from lorensiuswlt. So please add the AboutLibraries File to the correct location within your project. Thanks!

**Pull request merged**
